Algoritmo "CONTAR_REPITA"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 16/02/2024
Var
// Seção de Declarações das variáveiss
s, i: inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval("*----------*")
Escreval("--Contando--")
Repita
s <- s + 1
Escreval(s)
Ate (s = 10)


Fimalgoritmo