Algoritmo "Conversor"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 05/04/2023
Var
Angulo, Seno: real


Inicio
Escreva("Informe um angulo ")
Leia(Angulo)
Seno <- Sen(GraupRad(Angulo))
Escreva("O seno de:",Angulo, " é igual:", Seno)

Fimalgoritmo