Algoritmo "conversaotemp"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 18/01/2024
Var
celc : Real
faren: Real


Inicio
Escreva("Informa a temperatura em ºF ")
Leia(faren)
celc <- (faren - 32) / 1.8
Escreva(" A temperaturam em ºC é ", celc:4:1)


Fimalgoritmo