Algoritmo "ESTRUTURA_PARA"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 23/02/2024
Var
// Seção de Declarações das variáveis 
c: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Para c <- 1 ate 10 passo 1 faça
escreval(c)
FimPara

Fimalgoritmo