Algoritmo "Media"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 05/04/2023
Var
Media: real
Num1, Num2: real


Inicio
Escreva("Digite o primeiro numero: ")
Leia(Num1)
Escreva("Digite o segundo numero: ")
Leia(Num2)

Media <- (Num1+Num2)/2

Escreva("A media entre: ", Num1, " e",Num2, " é igual a:",Media)


Fimalgoritmo