Algoritmo "Soma"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 05/04/2023
Var
Num1: inteiro
Num2: inteiro
Soma: inteiro

Inicio
Escreva("Digite o primeiro numero ")
Leia(Num1)
Escreva("Digite o segundo numero ")
Leia(Num2)

Soma <- Num1+Num2

Escreva("A soma entre ", Num1, " e ", Num2, " é igual a ", Soma)



Fimalgoritmo