Algoritmo "SOMADOR"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 16/02/2024
Var
N, S, I: Inteiro


Inicio
s <- 0
i <- 1
Enquanto (i <=5) faça
Escreval("Digite o ", i, " ºnumero")
Leia(N)
S <- s + n
i<- i + 1
FimEnquanto
Escreva("A soma dos numeros digitados é: ", S)

Fimalgoritmo