Algoritmo "TAXAS"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 18/01/2024
Var
imposto: real
valor_ini: real


Inicio
Escreva ("Digite o valor do produto: ")
Leia(valor_ini)
imposto <- (valor_ini * 60)/100
Escreva ("O valor do imposto sobre este produto é: ", imposto)

Fimalgoritmo