Algoritmo "Valor absoluto"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 05/04/2023
Var
A: inteiro
B: real
C: real
D: real


Inicio
A <- abs(-50)
Escreval(A)

B <- Exp(9,5)
Escreval(B)

C <- RaizQ(90)
Escreval(C)

D <- Int(RaizQ(90))  //parte inteira da raiz
Escreval(D)

Fimalgoritmo